#!/bin/bash 
echo "--- INITIALISE INDEXING SCRIPT --- "
echo "==> Indexing cranfield collection..." 

java -cp target/my-app-1.0-SNAPSHOT.jar:lucene-8.6.2/core/lucene-core-8.6.2.jar:lucene-8.6.2/analysis/common/lucene-analyzers-common-8.6.2.jar:lucene-8.6.2/queryparser/lucene-queryparser-8.6.2.jar com.mycompany.app.IndexFiles
